customCommands:
  - key: "c"
    context: "files"
    description: "AI commit"
    command: 'git commit -m "{{.Form.Msg}}"'
    prompts:
      - type: "menuFromCommand"
        title: "AI Commit Message"
        key: "AiMsg"
        command: "/Users/dinethdesilva/.config/lazygit/scripts/ai-commit-msg.sh"
        filter: '^(?P<msg>.+)$'
        valueFormat: '{{.msg}}'
        labelFormat: '{{.msg | green}}'
      - type: "input"
        title: "Edit Commit Message"
        key: "Msg"
        initialValue: "{{.Form.AiMsg}}"
